### ISSUE TITLE
ttylog_open error when disconnecting before authentication attempt

### ISSUE THREAD

**Issue by mikkolehtisalo** [micheloosterhof/kippo#15]
So far I haven't got a successful session (except my own tests), and I'm wondering if kippo is to blame. I just get huge amounts of what seems to be connection dropped by the other end after *starting service ssh-userauth*, and after that AttributeError.

Am I just having bad luck or is there some kind of bug around?

```
2015-02-20 21:21:47+0200 [-] Log opened.
2015-02-20 21:21:47+0200 [-] twistd 14.0.0 (/usr/bin/python2 2.7.8) starting up.
2015-02-20 21:21:47+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2015-02-20 21:21:47+0200 [-] HoneyPotSSHFactory starting on 2222
2015-02-20 21:21:47+0200 [-] Starting factory <kippo.core.ssh.HoneyPotSSHFactory instance at 0x7ff300142560>
2015-02-20 21:28:58+0200 [kippo.core.ssh.HoneyPotSSHFactory] New connection: 115.239.228.35:60789 (192.168.1.10:2222) [session: 0]
2015-02-20 21:28:59+0200 [HoneyPotTransport,0,115.239.228.35] KEXINIT: client supported key exchange: ['diffie-hellman-group14-sha1', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1']
2015-02-20 21:28:59+0200 [HoneyPotTransport,0,115.239.228.35] KEXINIT: client supported public keys: ['ssh-rsa', 'ssh-dss']
2015-02-20 21:28:59+0200 [HoneyPotTransport,0,115.239.228.35] KEXINIT: client supported encryption: ['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes256-cbc', 'rijndael-cbc@lysator.liu.se', 'aes192-cbc', 'aes128-cbc', 'blowfish-cbc', 'arcfour128', 'arcfour', 'cast128-cbc', '3des-cbc']
2015-02-20 21:28:59+0200 [HoneyPotTransport,0,115.239.228.35] KEXINIT: client supported MAC: ['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com']
2015-02-20 21:28:59+0200 [HoneyPotTransport,0,115.239.228.35] KEXINIT: client supported compression: ['none']
2015-02-20 21:28:59+0200 [HoneyPotTransport,0,115.239.228.35] KEXINIT: client supported lang: ['']
2015-02-20 21:28:59+0200 [HoneyPotTransport,0,115.239.228.35] Remote SSH version: SSH-2.0-PUTTY
2015-02-20 21:28:59+0200 [HoneyPotTransport,0,115.239.228.35] kex alg, key alg: diffie-hellman-group-exchange-sha1 ssh-rsa
2015-02-20 21:28:59+0200 [HoneyPotTransport,0,115.239.228.35] outgoing: aes128-ctr hmac-sha1 none
2015-02-20 21:28:59+0200 [HoneyPotTransport,0,115.239.228.35] incoming: aes128-ctr hmac-sha1 none
2015-02-20 21:29:01+0200 [HoneyPotTransport,0,115.239.228.35] NEW KEYS
2015-02-20 21:29:01+0200 [HoneyPotTransport,0,115.239.228.35] starting service ssh-userauth
2015-02-20 21:29:03+0200 [HoneyPotTransport,0,115.239.228.35] Got remote error, code 11
	reason: 
2015-02-20 21:29:03+0200 [HoneyPotTransport,0,115.239.228.35] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 313, in runReactorWithLogging
	    reactor.run()
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
	    self.mainLoop()
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1204, in mainLoop
	    self.doIteration(t)
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 396, in doPoll
	    log.callWithLogger(selectable, _drdw, selectable, fd, event)
	--- <exception caught here> ---
	  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 88, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
	    self._disconnectSelectable(selectable, why, inRead)
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 260, in _disconnectSelectable
	    selectable.connectionLost(f)
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 298, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/user/kippo/kippo/core/ssh.py", line 230, in connectionLost
	    if self.ttylog_open:
	exceptions.AttributeError: HoneyPotTransport instance has no attribute 'ttylog_open'
```

**Comment by micheloosterhof** [comment]
Ah! I just pushed some changes earlier today, seems I didn't test those
100%. Let me fix that.!

**Comment by mikkolehtisalo** [comment]
Ok, you are correct! I tested the changes. Looks better now!

I'll wait for the prey then :)
